---

version: '3.8'

services:

    fastapi:
        container_name: onacut_back
        build: ./fastapi
        ports:
          - 8002:8000
        stdin_open: true 

    frontend:
        container_name: onacut_front
        build: ./frontend
        ports:
          - 3000:80
        stdin_open: true 
        depends_on:
            - fastapi
