name: Backend-ci

on:
  push:
    paths:
      - .github/workflows/backend-ci.yaml
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10

    - name: Install system dependencies
      run: make install-dev-deps

    - name: Run test on the CI
      run: make test
