name: FastApi-CI

on:
  push:
    paths:
      - .github/workflows/fastapi-ci.yaml
      - fastapi/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    defaults:
      run:
        working-directory: ./fastapi

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10

    - name: Install system dependencies
      run: make install-dev-deps

    - name: Run test on the CI
      run: make test
